import json
import os

WORK_DIR = 'workdir'
VECTOR_INDEX_FILE = f'{WORK_DIR}/vector_index.json'
LIST_INDEX_FILE = f'{WORK_DIR}/list_index.json'
KB_JSON_FILE = f'{WORK_DIR}/articles-docs.json'

LONGCHAIN_INDEX_FILE = f'{WORK_DIR}/longchain_index.json'
LONGCHAIN_DATA_STORE = f'{WORK_DIR}/longchain_data_store.pkl'


def load_creds():
    with open('credentials/access-tokens.json', 'r') as f:
        creds = json.load(f)
        os.environ["OPENAI_API_KEY"] = creds['openai_api_key']
        return creds


def save_index(vector_index, list_index):
    vector_index.save_to_disk(VECTOR_INDEX_FILE)
    list_index.save_to_disk(LIST_INDEX_FILE)


imunify_docs = {"git": "https://github.com/cloudlinux/imunify360-doc.git",
                "dir": "imunify360-doc",
                "url": "https://docs.imunify360.com/",
                "prefix": "imunify",
                "description": "Imunify360, ImunifyAV, Malware, Viruses, WAF, proactive defence, firewall, attacks, malware scanning, malware removal"
                }

cloudlinux_docs = {
    "git": "https://github.com/cloudlinux/cloudlinux-doc.git",
    "dir": "cloudlinux-doc",
    "url": "https://docs.cloudlinux.com/",
    "prefix": "cloudlinux",
    "description": "CloudLinux, CageFS, MySQL Governor aka Governor, PHP Selector, AccelerateWP, X-RAY, LVE, limits, lve-stats"
}

cln_docs = {
    "git": "https://github.com/cloudlinux/cln-doc.git",
    "dir": "cln-doc",
    "url": "https://docs.cln.cloudlinux.com/",
    "prefix": "cln",
    "description": "cln, billing, purchasing, invoices, payments, buying, credit card, activation keys, buying license, removing servers"
}

tuxcare_docs = {
    "git": "https://github.com/cloudlinux/tux-care-doc.git",
    "dir": "tux-care-doc",
    "url": "https://docs.tuxcare.com/",
    "prefix": "tuxcare",
    "description": "tuxcare, kernelcare, livepathcing, live patching, libcare, dbcare, virtcare, qemucare, kcarectl, kpatch, ksplice, kernel patching, ELS, AlmaCare"
}

# Generated by /Users/iseletsk/lve/randomHelpers/zendesk-kb-export.py
kb_articles = '/Users/iseletsk/lve/SupportBot/workdir/articles-docs.json'
